language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x

services:
  - mysql

env:
  - "PCT_TEST_MYSQL_DSN=\"root:@tcp(localhost:3306)/?parseTime=true\""

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.percona.com/apt precise testing'
    packages:
      - percona-toolkit

install:
  - "go get -u github.com/kardianos/govendor"
  - "govendor sync"

script:
  - mysql -e 'SELECT version();'
  - pt-summary --version
  - test/runner.sh

